<?php

/**
 * @file
 * Contains wid_country_news.module.
 */

use Drupal\wid_country_news\Controller\CountryNewsController;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function wid_country_news_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the wid_country_news module.
    case 'help.page.wid_country_news':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Adds country wise news module and block') . '</p>';
      return $output;
    default:
  }
}

/**
 * Implements hook_theme().
 */
function wid_country_news_theme() {
  $news = CountryNewsController::getCountryNews();
  return [
    'wid_country_news-block' => [
      'variables' => [
        'news' => $news,
      ],
    ],
  ];
}
